api/fakenewsdetection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/news/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm


app_name = 'news'

urlpatterns = [
    path('details/<int:pk>', views.news_detail, name='news_detail'),
    path('predict/', views.predict, name='predict'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html', authentication_form=LoginForm), name='login'),
    path('addNews/', views.addNews, name='addNews'),
    path('', views.index),
]

api/news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='images/', blank=True, null=True)
    content = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    prediction = models.CharField(max_length=255, null=True, blank=True)
    publishedBy = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.title 

api/news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from news.models import News

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

class AddNewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content', 'picture']
    
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))
    
    picture = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'w-full py-4 px-6 rounded shadow',
    }))

api/news/views.py
from django.shortcuts import get_object_or_404, render
from news.models import News
from news.predictions_service import get_prediction
from news.forms import SignupForm, AddNewsForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

def index(request):
    query = request.GET.get('query','')
    news = News.objects.all().order_by('published')

    if query:
        news = news.filter(prediction__exact=query)

    return render(request, 'index.html', {
        'news': news,
        'query': query,
    })

def news_detail(request, pk):
    news = get_object_or_404(News, pk=pk)
    
    return render(request, 'news.html', {
        'news': news,
    })

def predict(request):
    news_detail = request.GET.get('predict','')
    prediction = get_prediction(news_detail)
    return render(request, 'predictions.html', {
        'prediction': prediction,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {
        'form': form,
    })

@login_required
def addNews(request):
    if request.method == 'POST':
        form = AddNewsForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.publishedBy = request.user
            item.prediction = get_prediction(item.content)
            item.save()

            return redirect('/news/')
    else:
        form = AddNewsForm()

    return render(request, 'add_news.html', {
        'form': form,
    })

api/news/templates/add_news.html
{% extends 'base.html' %}

{% block title %} Add news {% endblock %}

{% block content %}
<div class="w-1/3 my-6 mx-auto p-8 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Add news </h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

api/news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="templates/index.css">
    <title>{% block title %}{% endblock %} | News</title>
</head>
<body class="flex flex-col min-h-screen">
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/news" class="text-2xl font-bold text-blue-600 px-2 py-1">FactChecker</a>

        <div class="space-x-6 flex items-center">
            <a href="/news/predict/" class="inline-block px-3 py-1 text-lg font-bold text-white bg-blue-600 hover:bg-blue-900 transition duration-300 ease-in-out">Check your content</a>

            {% if user.is_authenticated %}
                <a href="/news/addNews/" class="text-lg font-bold text-blue-600 hover:text-blue-900">New Article</a>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="text-lg font-bold text-red-600 hover:text-red-900">Logout</button>
                </form>
            {% else %}
                <a href="/news/login/" class="text-lg pr-10 font-bold text-balck-600 hover:text-blue-900">Login</a>
            {% endif %}
        </div>
    </nav>

    <main class="flex-grow">
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer class="py-6 px-6 flex justify-between bg-gray-700 mt-auto">
        <div class="w-2/3 pr-10">
            <p class="text-lg text-white">All rights reserved</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-white">Menu</h3>

            <ul class="space-y-2">
                <li><a href="/news/" class="text-lg text-blue-500 hover:text-white">News</a></li>
                <li><a href="/news/predict/" class="text-lg text-blue-500 hover:text-white">Check your content</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

api/news/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="p-4 flex">
    <p class="text-lg font-bold mt-4 mr-8">Filter articles:</p>
    <a href="/news/?query=reliable" class="filter-link border border-green-500 text-green-500 hover:bg-green-500 hover:text-white">Reliable</a>
    <a href="/news/?query=not reliable" class="filter-link border border-red-500 text-red-500 hover:bg-red-500 hover:text-white">Not reliable</a>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <div class="grid grid-cols-3 gap-20">
        {% for item in news %}
            <div class="flex flex-col overflow-hidden transition duration-300 transform hover:shadow-lg hover:scale-105 hover:bg-gray-100 hover:border-indigo-500 border border-gray-200 rounded-xl">
                <a href="{% url 'news:news_detail' item.id %}">
                    <div class="mb-2">
                        <img src="{{ item.picture.url }}" class="rounded-t-xl w-full h-48 object-cover transition duration-300 transform hover:scale-110">
                    </div>
    
                    <div class="p-6 rounded-b-xl">
                        <h2 class="text-lg font-semibold text-black-700 mb-2 hover:text-blue-900">{{ item.title }}</h2>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div> 
</div>
{% endblock %}

api/news/templates/login.html
{% extends 'base.html' %}

{% block title %}
Log in
{% endblock %}

{% block content %}
<div class="w-1/3 my-6 mx-auto p-8 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form action="." method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="username" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="password" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        
        <div class="text-center mb-4 mt-8">
            <a href="{% url 'news:signup' %}" class="underline block mb-2 hover:text-blue-600">Don't have an account? Sign up...</a>
            <button class="w-full py-4 px-6 rounded text-lg bg-blue-500 hover:bg-blue-700 text-white">Log in</button>
        </div>               
    </form>
</div>
{% endblock %}

api/news/templates/news.html
{% extends 'base.html' %}

{% block title %}{{ news.title}}{% endblock %}

{% block content %}
<div class="max-w-2xl mx-auto p-4">
    <h1 class="text-3xl font-mono text-gray-700 font-bold">{{ news.title }}</h1>
</div>

<div class="max-w-2xl mx-auto p-4 bg-white shadow-lg rounded-lg">
    
    <p class="text-sm text-gray-600">Published by: {{ news.publishedBy }}</p>
    <div class="flex justify-between">
        <p class="text-sm text-gray-600">{{ news.published }}</p>
        <p class="text-sm font-bold {% if news.prediction == 'reliable' %}text-green-600{% else %}text-red-600{% endif %}">This content is {{ news.prediction }}</p>
    </div>

    <div class="mb-4">
        <img src="{{ news.picture.url }}" class="mt-4 object-cover w-full h-64 rounded">
    </div>

    <div class="pt-10 text-gray-700">
        <p class="text-lg leading-7 mb-4">{{ news.content }}</p>
    </div>  
</div>
{% endblock %}

api/news/templates/predictions.html
{% extends 'base.html' %}

{% block title %}Predictions{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <div class="flex flex-col items-center justify-center mb-8">
        <form action="/news/predict/" method="get" class="flex flex-col items-center">
            <div class="relative w-96 mb-4">
                <textarea name="predict" placeholder="Enter text..." rows="6" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500 transition duration-300 resize-none"></textarea>
            </div>
            <input type="submit" value="Check if reliable" class="px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none transition duration-300">
        </form>
        {% if prediction and request.GET.predict %}
        <div class="text-center mt-4">
            <p class="{% if prediction == 'reliable' %}text-green-600{% else %}text-red-600{% endif %}">This content is {{ prediction }}</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

api/news/templates/signup.html
{% extends 'base.html' %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<div class="w-1/3 my-6 mx-auto p-8 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form action="." method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="username" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="email" class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label for="password1" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label for="password2" class="block text-gray-700 text-sm font-bold mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <div class="text-center mb-4 mt-8">
            <a href="{% url 'news:login' %}" class="underline block mb-2 hover:text-blue-600">Already have an account? Log in...</a>
            <button class="w-full py-4 px-6 rounded text-lg bg-blue-500 hover:bg-blue-700 text-white">Sign up</button>
        </div>  
    </form>
</div>
{% endblock %}